# This workflow is part of the Continous Integration workflow in ci.yaml however it is
# running on its own since it has jobs that execute on a scheduled routine unlike the jobs
# in ci.yaml.
name: Security (CI)
on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [main]

  schedule:
    - cron: '30 2 * * *' # for scheduled security scans

jobs:
  check-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v4

      - name: Scan for vulnerable dependencies
        uses: aquasecurity/trivy-action@b6643a29fecd7f34b3597bc6acb0a98b03d33ff8 # 0.33.1
        id: deps
        with:
          scan-type: fs
          scanners: vuln
          severity: 'CRITICAL,HIGH'
          exit-code: '1'

  check-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v4

      - name: Scan for vulnerable dependencies
        uses: aquasecurity/trivy-action@b6643a29fecd7f34b3597bc6acb0a98b03d33ff8 # 0.33.1
        id: deps
        with:
          scan-type: fs
          scanners: 'secret,misconfig'
          severity: 'CRITICAL,HIGH'
          exit-code: '1'
